/**
 * PitchDesign.tsx — Pitch Design Recommendations Page
 *
 * Displays actionable pitch design recommendations for each pitcher based on
 * comparison to MLB population norms across 6 categories:
 *   extension | movement | spin | sequencing | mix | command
 *
 * Data source: /data/pitch_design.json (generated by models/pitch_design_recs.py)
 * Grouped by pitcher → sorted by recommendation rank → rendered as coaching cards.
 */

import { useState, useMemo, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { useData } from '../data/useData';
import { useScoringConfig } from '../data/useScoringConfig';
import { fetchJson } from '../data/fetchJson';
import { SkeletonPage } from '../components/Skeleton';
import { InlineSearch } from '../components/InlineSearch';
import type { Pitcher } from '../types';

// ── Types ─────────────────────────────────────────────────────────────────────

interface DesignRecommendation {
  rank: number;
  category: string;
  target_pitch_type: string;
  metric: string;
  current_value: number | null;
  target_value: number | null;
  projected_gain: number | null;
  text: string;
}

interface DesignPitcherData {
  pitcher_name: string;
  pitcher_team: string;
  pitch_plus: number;
  recommendations: DesignRecommendation[];
}

interface PitchDesignData {
  generated: string;
  n_pitchers: number;
  pitchers: Record<string, DesignPitcherData>;
}

// ── Category display config ───────────────────────────────────────────────────

const CATEGORY_CONFIG: Record<string, { label: string; color: string; icon: string }> = {
  extension:  { label: 'Extension',  color: '#4a9eff', icon: '→' },
  movement:   { label: 'Movement',   color: '#a78bfa', icon: '↗' },
  spin:       { label: 'Spin',       color: '#f59e0b', icon: '⟳' },
  sequencing: { label: 'Sequencing', color: '#34d399', icon: '⇄' },
  mix:        { label: 'Mix',        color: '#fb923c', icon: '+' },
  command:    { label: 'Command',    color: '#f472b6', icon: '◎' },
};

const ALL_CATEGORIES = Object.keys(CATEGORY_CONFIG);

// ── Gap Bar component ─────────────────────────────────────────────────────────

function GapBar({
  current,
  target,
  direction = 'higher',
  color,
}: {
  current: number | null;
  target: number | null;
  direction?: 'higher' | 'lower';
  color: string;
}) {
  if (current === null || target === null) return null;

  const gap = Math.abs(target - current);
  const isPositive = direction === 'higher' ? target > current : target < current;
  // Show fill as % of target; cap at 100%
  const fillPct = Math.min(100, (current / Math.max(target, current)) * 100);

  return (
    <div style={{ marginTop: 6 }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 11,
                    color: '#9ca3af', marginBottom: 3 }}>
        <span>Current: <strong style={{ color: 'var(--text-1)' }}>{current.toFixed(2)}</strong></span>
        <span>Target: <strong style={{ color }}>{target.toFixed(2)}</strong></span>
      </div>
      <div style={{
        height: 6, background: '#1e293b', borderRadius: 3, overflow: 'hidden',
      }}>
        <div style={{
          height: '100%',
          width: `${fillPct}%`,
          background: isPositive ? '#ef4444' : color,  // red if below target, blue/color if above
          borderRadius: 3,
          transition: 'width 0.4s ease',
        }} />
      </div>
      <div style={{ fontSize: 10, color: 'var(--text-3)', marginTop: 2 }}>
        Gap: {gap.toFixed(2)} {isPositive ? '↑ needs improvement' : '✓ above target'}
      </div>
    </div>
  );
}

// ── Recommendation Card ───────────────────────────────────────────────────────

function RecommendationCard({ rec }: { rec: DesignRecommendation }) {
  const cfg = CATEGORY_CONFIG[rec.category] ?? { label: rec.category, color: 'var(--text-3)', icon: '·' };
  const gainStr = rec.projected_gain != null
    ? `+${rec.projected_gain.toFixed(1)} Pitch+`
    : '';

  return (
    <div style={{
      background: 'var(--bg-input)',
      border: `1px solid ${cfg.color}33`,
      borderRadius: 10,
      padding: '14px 16px',
      marginBottom: 10,
    }}>
      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                    marginBottom: 8 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <span style={{
            background: `${cfg.color}22`, color: cfg.color,
            borderRadius: 6, padding: '2px 8px', fontSize: 11, fontWeight: 600,
          }}>
            {cfg.icon} {cfg.label}
          </span>
          {rec.target_pitch_type && rec.target_pitch_type !== 'ALL' && (
            <span style={{
              background: '#1e293b', color: '#94a3b8',
              borderRadius: 4, padding: '2px 6px', fontSize: 10,
            }}>
              {rec.target_pitch_type}
            </span>
          )}
        </div>
        {gainStr && (
          <span style={{
            background: '#16a34a22', color: '#4ade80',
            borderRadius: 6, padding: '2px 8px', fontSize: 11, fontWeight: 600,
          }}>
            {gainStr} projected
          </span>
        )}
      </div>

      {/* Recommendation text */}
      <p style={{ margin: 0, color: '#cbd5e1', fontSize: 13, lineHeight: 1.5 }}>
        {rec.text}
      </p>

      {/* Gap bar */}
      <GapBar
        current={rec.current_value}
        target={rec.target_value}
        color={cfg.color}
      />
    </div>
  );
}

// ── Pitcher Panel ─────────────────────────────────────────────────────────────

function PitcherPanel({
  pitcherId,
  pitcherData,
  activeCategory,
}: {
  pitcherId: string;
  pitcherData: DesignPitcherData;
  activeCategory: string;
}) {
  const filtered = activeCategory === 'all'
    ? pitcherData.recommendations
    : pitcherData.recommendations.filter((r) => r.category === activeCategory);

  if (filtered.length === 0) return null;

  const totalGain = pitcherData.recommendations
    .reduce((sum, r) => sum + (r.projected_gain ?? 0), 0);

  return (
    <div style={{
      background: 'var(--bg-surface)',
      border: '1px solid var(--border-plus)',
      borderRadius: 12,
      padding: '18px 20px',
      marginBottom: 20,
    }}>
      {/* Pitcher header */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                    marginBottom: 14 }}>
        <div>
          <Link
            to={`/player/${pitcherId}`}
            style={{ color: '#4a9eff', textDecoration: 'none', fontSize: 17, fontWeight: 700 }}
          >
            {pitcherData.pitcher_name}
          </Link>
          <span style={{ color: 'var(--text-3)', marginLeft: 10, fontSize: 13 }}>
            {pitcherData.pitcher_team}
          </span>
        </div>
        <div style={{ display: 'flex', gap: 12, alignItems: 'center' }}>
          <div style={{ textAlign: 'right' }}>
            <div style={{ fontSize: 11, color: 'var(--text-3)' }}>Pitch+</div>
            <div style={{ fontSize: 20, fontWeight: 700, color: 'var(--text-1)' }}>
              {pitcherData.pitch_plus}
            </div>
          </div>
          {totalGain > 0 && (
            <div style={{
              background: '#16a34a22', border: '1px solid #16a34a44',
              borderRadius: 8, padding: '6px 12px', textAlign: 'center',
            }}>
              <div style={{ fontSize: 10, color: '#4ade80' }}>Potential gain</div>
              <div style={{ fontSize: 16, fontWeight: 700, color: '#4ade80' }}>
                +{totalGain.toFixed(1)}
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Recommendations */}
      {filtered.map((rec) => (
        <RecommendationCard key={`${rec.rank}-${rec.metric}`} rec={rec} />
      ))}
    </div>
  );
}

// ── Main page ─────────────────────────────────────────────────────────────────

// ── What-If Simulator ─────────────────────────────────────────────────────────
// Uses population_stats from scoring_config to compute grade delta for
// a given change in a raw metric. Formula: delta_grade = delta_raw / std * 15

interface SimMetric {
  key: string;
  label: string;
  unit: string;
  step: number;
  min: number;
  max: number;
}

const SIM_METRICS: SimMetric[] = [
  { key: 'avg_velo', label: 'Fastball Velocity', unit: 'mph', step: 0.5, min: -5, max: 5 },
  { key: 'avg_spin', label: 'Spin Rate', unit: 'rpm', step: 50, min: -500, max: 500 },
  { key: 'avg_ivb', label: 'Induced Vertical Break', unit: '"', step: 1, min: -8, max: 8 },
  { key: 'avg_hb', label: 'Horizontal Break', unit: '"', step: 1, min: -8, max: 8 },
  { key: 'avg_ext', label: 'Extension', unit: 'ft', step: 0.1, min: -1, max: 1 },
];

function WhatIfSimulator({ pitchers }: { pitchers: Pitcher[] }) {
  const { config } = useScoringConfig();
  const [selected, setSelected] = useState<Pitcher | null>(null);
  const [deltas, setDeltas] = useState<Record<string, number>>({});

  const stats = config?.population_stats ?? {};

  const projectedDelta = useMemo(() => {
    if (!config) return 0;
    let total = 0;
    for (const [key, delta] of Object.entries(deltas)) {
      if (delta === 0) continue;
      const ps = stats[key];
      if (ps?.std && ps.std > 0) {
        total += (delta / ps.std) * 15;
      }
    }
    return total;
  }, [deltas, stats]);

  const basePitchPlus = selected?.pitch_plus ?? 100;
  const projectedPitchPlus = Math.round(Math.max(20, Math.min(180, basePitchPlus + projectedDelta)));

  const deltaColor = projectedDelta > 2 ? '#34d399' : projectedDelta < -2 ? '#ef4444' : '#a0a0b8';

  return (
    <div className="card" style={{ padding: '20px 24px' }}>
      <h3 style={{ margin: '0 0 16px', fontSize: 16, color: '#e0e0e8' }}>
        ⚗ What-If Simulator
        <span style={{ fontSize: 11, color: '#606080', fontWeight: 400, marginLeft: 8 }}>
          Adjust pitch properties and see projected Pitch+ impact
        </span>
      </h3>

      <div style={{ marginBottom: 16, maxWidth: 320 }}>
        <div style={{ fontSize: 11, color: '#a0a0b8', marginBottom: 4 }}>SELECT PITCHER</div>
        <InlineSearch<Pitcher>
          items={pitchers}
          getKey={p => p.pitcher_id}
          getLabel={p => p.pitcher_name}
          value={selected}
          onSelect={setSelected}
          placeholder="Choose a pitcher…"
          maxResults={8}
        />
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(240px, 1fr))', gap: 16 }}>
        {SIM_METRICS.map(metric => {
          const delta = deltas[metric.key] ?? 0;
          const ps = stats[metric.key];
          const gradeImpact = ps?.std ? (delta / ps.std) * 15 : 0;
          return (
            <div key={metric.key}>
              <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 4 }}>
                <span style={{ fontSize: 12, color: '#a0a0b8' }}>{metric.label}</span>
                <span style={{ fontSize: 12, fontFamily: 'monospace', color: delta !== 0 ? deltaColor : '#606080' }}>
                  {delta > 0 ? '+' : ''}{delta.toFixed(1)} {metric.unit}
                  {gradeImpact !== 0 && (
                    <span style={{ marginLeft: 6, fontSize: 10, color: gradeImpact > 0 ? '#34d399' : '#ef4444' }}>
                      ({gradeImpact > 0 ? '+' : ''}{gradeImpact.toFixed(1)} pts)
                    </span>
                  )}
                </span>
              </div>
              <input
                type="range"
                min={metric.min}
                max={metric.max}
                step={metric.step}
                value={delta}
                onChange={e => setDeltas(prev => ({ ...prev, [metric.key]: parseFloat(e.target.value) }))}
                style={{ width: '100%', accentColor: 'var(--accent)' }}
              />
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 10, color: '#404060' }}>
                <span>{metric.min > 0 ? '+' : ''}{metric.min}</span>
                <span>0</span>
                <span>+{metric.max}</span>
              </div>
            </div>
          );
        })}
      </div>

      {/* Summary */}
      <div style={{ marginTop: 20, padding: '14px 16px', background: '#0c1829', borderRadius: 8, border: '1px solid #1e2a3e', display: 'flex', alignItems: 'center', gap: 20, flexWrap: 'wrap' }}>
        <div>
          <div style={{ fontSize: 10, color: '#606080', marginBottom: 2 }}>CURRENT PITCH+</div>
          <div style={{ fontSize: 24, fontWeight: 700, color: '#e0e0e8' }}>{basePitchPlus}</div>
        </div>
        <div style={{ fontSize: 24, color: '#2a2a3e' }}>→</div>
        <div>
          <div style={{ fontSize: 10, color: '#606080', marginBottom: 2 }}>PROJECTED PITCH+</div>
          <div style={{ fontSize: 24, fontWeight: 700, color: deltaColor }}>{projectedPitchPlus}</div>
        </div>
        {projectedDelta !== 0 && (
          <div style={{ marginLeft: 'auto' }}>
            <div style={{ fontSize: 10, color: '#606080', marginBottom: 2 }}>NET CHANGE</div>
            <div style={{ fontSize: 20, fontWeight: 700, color: deltaColor }}>
              {projectedDelta > 0 ? '+' : ''}{projectedDelta.toFixed(1)} pts
            </div>
          </div>
        )}
        {projectedDelta !== 0 && (
          <button
            onClick={() => setDeltas({})}
            style={{ padding: '5px 12px', fontSize: 11, borderRadius: 6, border: '1px solid #2a2a3e', background: 'transparent', color: '#606080', cursor: 'pointer' }}
          >
            Reset
          </button>
        )}
      </div>

      <div style={{ marginTop: 8, fontSize: 10, color: '#404060' }}>
        Grade impact estimated from population standard deviations in scoring config. One standard deviation change = ±15 Pitch+ points.
      </div>
    </div>
  );
}

export function PitchDesign() {
  const { data, loading: pitcherLoading } = useData();
  const [designData, setDesignData] = useState<PitchDesignData | null>(null);
  const [designLoading, setDesignLoading] = useState(true);
  const [designError, setDesignError] = useState<string | null>(null);

  // Filter state
  const [search, setSearch] = useState('');
  const [activeCategory, setActiveCategory] = useState('all');
  const [minPitchPlus, setMinPitchPlus] = useState(0);
  const [teamFilter, setTeamFilter] = useState('All');
  const [sortBy, setSortBy] = useState<'pitch_plus' | 'recs' | 'gain'>('pitch_plus');

  // Load pitch_design.json
  useEffect(() => {
    fetchJson<PitchDesignData>('/data/pitch_design.json')
      .then((d) => { setDesignData(d); setDesignLoading(false); })
      .catch((e) => { setDesignError(e.message); setDesignLoading(false); });
  }, []);

  // Teams list from pitcher data
  const teams = useMemo(() => {
    if (!data) return [];
    const s = new Set(data.pitchers.pitchers.map((p) => p.pitcher_team));
    return ['All', ...Array.from(s).sort()];
  }, [data]);

  // Filtered + sorted pitcher list
  const pitcherEntries = useMemo(() => {
    if (!designData) return [];
    let entries = Object.entries(designData.pitchers)
      .filter(([, pd]) => pd.recommendations.length > 0);

    if (search) {
      const q = search.toLowerCase();
      entries = entries.filter(([, pd]) =>
        pd.pitcher_name.toLowerCase().includes(q) ||
        pd.pitcher_team.toLowerCase().includes(q)
      );
    }
    if (teamFilter !== 'All') {
      entries = entries.filter(([, pd]) => pd.pitcher_team === teamFilter);
    }
    if (minPitchPlus > 0) {
      entries = entries.filter(([, pd]) => pd.pitch_plus >= minPitchPlus);
    }
    if (activeCategory !== 'all') {
      entries = entries.filter(([, pd]) =>
        pd.recommendations.some((r) => r.category === activeCategory)
      );
    }

    // Sort
    entries.sort(([, a], [, b]) => {
      if (sortBy === 'pitch_plus') return b.pitch_plus - a.pitch_plus;
      if (sortBy === 'recs') return b.recommendations.length - a.recommendations.length;
      if (sortBy === 'gain') {
        const ga = a.recommendations.reduce((s, r) => s + (r.projected_gain ?? 0), 0);
        const gb = b.recommendations.reduce((s, r) => s + (r.projected_gain ?? 0), 0);
        return gb - ga;
      }
      return 0;
    });

    return entries;
  }, [designData, search, teamFilter, minPitchPlus, activeCategory, sortBy]);

  if (pitcherLoading || designLoading) return <SkeletonPage />;

  if (designError) {
    return (
      <div style={{ padding: 40, color: '#ef4444', fontFamily: 'monospace' }}>
        <h2>Pitch Design data not available</h2>
        <p>{designError}</p>
        <p style={{ color: '#94a3b8' }}>
          Run <code>python models/pitch_design_recs.py</code> to generate pitch_design.json.
        </p>
      </div>
    );
  }

  return (
    <div style={{ maxWidth: 960, margin: '0 auto', padding: '24px 20px' }}>
      {/* Page header */}
      <div style={{ marginBottom: 28 }}>
        <h1 style={{ fontSize: 26, fontWeight: 700, color: 'var(--text-1)', margin: 0 }}>
          Pitch Design Lab
        </h1>
        <p style={{ color: 'var(--text-3)', marginTop: 6, fontSize: 14 }}>
          Data-driven pitch design recommendations for{' '}
          <strong style={{ color: '#94a3b8' }}>{designData?.n_pitchers ?? 0}</strong> pitchers
          based on MLB population norms.
          {designData?.generated && (
            <span style={{ color: 'var(--text-4)', marginLeft: 8 }}>
              Generated {designData.generated}
            </span>
          )}
        </p>
      </div>

      {/* Category filter tabs */}
      <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', marginBottom: 20 }}>
        {['all', ...ALL_CATEGORIES].map((cat) => {
          const cfg = cat === 'all'
            ? { label: 'All', color: '#94a3b8' }
            : (CATEGORY_CONFIG[cat] ?? { label: cat, color: '#94a3b8' });
          return (
            <button
              key={cat}
              onClick={() => setActiveCategory(cat)}
              style={{
                padding: '5px 14px',
                borderRadius: 20,
                border: `1px solid ${activeCategory === cat ? cfg.color : '#1e293b'}`,
                background: activeCategory === cat ? `${cfg.color}22` : 'transparent',
                color: activeCategory === cat ? cfg.color : 'var(--text-3)',
                cursor: 'pointer',
                fontSize: 12,
                fontWeight: 600,
                transition: 'all 0.15s',
              }}
            >
              {cfg.label}
            </button>
          );
        })}
      </div>

      {/* Controls */}
      <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap', marginBottom: 24,
                    alignItems: 'center' }}>
        <input
          placeholder="Search pitcher or team…"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          style={{
            background: 'var(--bg-input)', border: '1px solid var(--border-plus)', borderRadius: 8,
            color: 'var(--text-1)', padding: '7px 12px', fontSize: 13, flex: '1 1 180px',
          }}
        />
        <select
          value={teamFilter}
          onChange={(e) => setTeamFilter(e.target.value)}
          style={{
            background: 'var(--bg-input)', border: '1px solid var(--border-plus)', borderRadius: 8,
            color: 'var(--text-1)', padding: '7px 10px', fontSize: 13,
          }}
        >
          {teams.map((t) => <option key={t}>{t}</option>)}
        </select>
        <select
          value={sortBy}
          onChange={(e) => setSortBy(e.target.value as typeof sortBy)}
          style={{
            background: 'var(--bg-input)', border: '1px solid var(--border-plus)', borderRadius: 8,
            color: 'var(--text-1)', padding: '7px 10px', fontSize: 13,
          }}
        >
          <option value="pitch_plus">Sort: Pitch+ (high→low)</option>
          <option value="recs">Sort: Most Recommendations</option>
          <option value="gain">Sort: Most Projected Gain</option>
        </select>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <label style={{ color: 'var(--text-3)', fontSize: 12 }}>Min Pitch+</label>
          <input
            type="number"
            value={minPitchPlus || ''}
            onChange={(e) => setMinPitchPlus(Number(e.target.value) || 0)}
            placeholder="0"
            style={{
              width: 60, background: 'var(--bg-input)', border: '1px solid var(--border-plus)',
              borderRadius: 8, color: 'var(--text-1)', padding: '7px 8px', fontSize: 13,
            }}
          />
        </div>
      </div>

      {/* What-If Simulator */}
      {data && (
        <div style={{ marginBottom: 24 }}>
          <WhatIfSimulator pitchers={data.pitchers.pitchers} />
        </div>
      )}

      {/* Results count */}
      <div style={{ color: 'var(--text-4)', fontSize: 12, marginBottom: 16 }}>
        Showing {pitcherEntries.length} pitchers
      </div>

      {/* Pitcher panels */}
      {pitcherEntries.length === 0 ? (
        <div style={{ color: 'var(--text-3)', padding: 40, textAlign: 'center' }}>
          No pitchers match the current filters.
        </div>
      ) : (
        pitcherEntries.map(([pitcherId, pd]) => (
          <PitcherPanel
            key={pitcherId}
            pitcherId={pitcherId}
            pitcherData={pd}
            activeCategory={activeCategory}
          />
        ))
      )}
    </div>
  );
}
