/**
 * NovelMetricsPanel.tsx
 *
 * Displays all 14 novel pitching metrics for a pitcher with:
 *   - Current value + formatted display
 *   - 5-year SVG sparkline trend (2021-2025)
 *   - ERA correlation bar (|r_test| → bar length)
 *   - Validation status badge (STRONG / WORTH / STABLE)
 *   - Pitch+ dimension tag (which model dimension uses this metric)
 *
 * Data sourced from useNovelMetrics() hook → /data/novel_metrics.json
 * Generated by: models/export_novel_metrics_json.py
 */

import { useMemo } from 'react';
import { useNovelMetrics, sortedByPredictiveness } from '../data/useNovelMetrics';
import type { NovelMetricKey, MetricMeta, YearMetrics } from '../data/useNovelMetrics';

const YEARS = ['2021', '2022', '2023', '2024', '2025'];

// ── Status badge config ────────────────────────────────────────────────────────

const STATUS_CONFIG: Record<string, { label: string; color: string; bg: string }> = {
  STRONG: { label: 'Strong',  color: '#10b981', bg: 'rgba(16,185,129,0.12)' },
  WORTH:  { label: 'Worth',   color: '#3b82f6', bg: 'rgba(59,130,246,0.12)' },
  STABLE: { label: 'Stable',  color: '#f59e0b', bg: 'rgba(245,158,11,0.12)' },
  '':     { label: '',        color: '',        bg: '' },
};

// ── Grouping ───────────────────────────────────────────────────────────────────

// Metrics already wired into PITCH_PLUS_DIMENSIONS
const IN_MODEL: NovelMetricKey[] = [
  'swing_rv_against', 'in_zone_swing_rv', 'chase_swing_rv',
  'bip_adjusted_kbb', 'bip_rate', 'take_rv_against', 'race_to_2_strikes',
];

// Metrics validated but used for research/design only
const RESEARCH: NovelMetricKey[] = [
  'count_leverage_delta', 'memory_decay_effect', 'arsenal_complementarity',
  'first_pitch_skill', 'first_pitch_cascade',
];

// Physical properties — high stability, not ERA-predictive
const PHYSICAL: NovelMetricKey[] = ['grav_dev_fb', 'grav_dev_all'];

// ── Sparkline ──────────────────────────────────────────────────────────────────

function Sparkline({
  values,
  direction,
  width = 72,
  height = 26,
}: {
  values: (number | null)[];
  direction: 'lower' | 'higher';
  width?: number;
  height?: number;
}) {
  const pts = values.filter(v => v !== null) as number[];
  if (pts.length < 2) {
    return <span style={{ width, height, display: 'inline-block', opacity: 0.2 }}>—</span>;
  }

  const min = Math.min(...pts);
  const max = Math.max(...pts);
  const range = max - min || 1;

  const points = values.map((v, i) => {
    if (v === null) return null;
    const x = (i / (values.length - 1)) * (width - 4) + 2;
    const y = height - 4 - ((v - min) / range) * (height - 8);
    return { x, y };
  });

  const validPts = points.filter(Boolean) as { x: number; y: number }[];
  const pathD = validPts.map((p, i) => `${i === 0 ? 'M' : 'L'} ${p.x.toFixed(1)} ${p.y.toFixed(1)}`).join(' ');

  // Color by trend direction: if improving (going in the "better" direction) → positive color
  const last  = pts[pts.length - 1];
  const first = pts[0];
  const improving = direction === 'lower' ? last < first : last > first;
  const trendColor = improving ? '#10b981' : '#f43f5e';
  const lastPt = validPts[validPts.length - 1];

  return (
    <svg width={width} height={height} style={{ overflow: 'visible', flexShrink: 0 }}>
      <path d={pathD} fill="none" stroke={trendColor} strokeWidth={1.5} strokeLinecap="round" strokeLinejoin="round" opacity={0.7} />
      {/* Endpoint dot */}
      {lastPt && (
        <circle cx={lastPt.x} cy={lastPt.y} r={2.5} fill={trendColor} />
      )}
    </svg>
  );
}

// ── Correlation bar ────────────────────────────────────────────────────────────

function CorrelationBar({ r }: { r: number }) {
  const abs = Math.min(Math.abs(r), 1);
  const pct = abs * 100;
  const color = abs >= 0.5 ? '#10b981' : abs >= 0.2 ? '#3b82f6' : '#4a6580';
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 5, minWidth: 90 }}>
      <div style={{
        flex: 1, height: 5, background: 'var(--border)', borderRadius: 3, overflow: 'hidden',
      }}>
        <div style={{ width: `${pct}%`, height: '100%', background: color, borderRadius: 3, transition: 'width 0.4s ease' }} />
      </div>
      <span style={{ fontSize: 10, fontFamily: 'var(--mono)', color: 'var(--text-3)', minWidth: 30 }}>
        {r >= 0 ? '+' : ''}{r.toFixed(2)}
      </span>
    </div>
  );
}

// ── Format metric value ────────────────────────────────────────────────────────

function fmtValue(key: NovelMetricKey, v: number | null | undefined): string {
  if (v === null || v === undefined) return '—';
  if (['bip_rate', 'bip_adjusted_kbb', 'k_rate', 'bb_rate'].includes(key)) {
    return `${(v * 100).toFixed(1)}%`;
  }
  if (['swing_rv_against', 'take_rv_against', 'in_zone_swing_rv', 'chase_swing_rv'].includes(key)) {
    return v.toFixed(3);
  }
  if (['race_to_2_strikes'].includes(key)) {
    return v.toFixed(2);
  }
  if (Math.abs(v) < 0.01) return v.toFixed(4);
  if (Math.abs(v) < 1)    return v.toFixed(3);
  return v.toFixed(2);
}

// ── Metric row ─────────────────────────────────────────────────────────────────

function MetricRow({
  metricKey,
  meta,
  yearMetrics,
}: {
  metricKey: NovelMetricKey;
  meta: MetricMeta;
  yearMetrics: (number | null)[];
}) {
  const current = yearMetrics[yearMetrics.length - 1];
  const hasData = yearMetrics.some(v => v !== null);
  const status = STATUS_CONFIG[meta.status] ?? STATUS_CONFIG[''];

  return (
    <tr style={{ borderBottom: '1px solid var(--border)', opacity: hasData ? 1 : 0.45 }}>
      {/* Metric name */}
      <td style={{ padding: '8px 12px', fontSize: 12, color: 'var(--text-1)', whiteSpace: 'nowrap' }}>
        {meta.label}
      </td>

      {/* Dimension badge */}
      <td style={{ padding: '8px 6px', whiteSpace: 'nowrap' }}>
        {meta.dim !== '—' && (
          <span style={{
            fontSize: 9, fontWeight: 600, padding: '2px 6px',
            background: 'var(--border)', borderRadius: 3,
            color: 'var(--text-3)', textTransform: 'uppercase', letterSpacing: '0.05em',
          }}>
            {meta.dim}
          </span>
        )}
      </td>

      {/* Current value */}
      <td style={{ padding: '8px 12px', fontFamily: 'var(--mono)', fontSize: 13,
                   color: 'var(--text-1)', textAlign: 'right', whiteSpace: 'nowrap' }}>
        {fmtValue(metricKey, current)}
      </td>

      {/* Direction */}
      <td style={{ padding: '8px 6px', fontSize: 11, color: meta.direction === 'lower' ? '#f43f5e' : '#10b981',
                   textAlign: 'center', fontFamily: 'var(--mono)' }}>
        {meta.direction === 'lower' ? '↓' : '↑'}
      </td>

      {/* 5-yr sparkline */}
      <td style={{ padding: '4px 12px' }}>
        <Sparkline values={yearMetrics} direction={meta.direction} />
      </td>

      {/* ERA correlation bar */}
      <td style={{ padding: '8px 12px', minWidth: 100 }}>
        <CorrelationBar r={meta.r_test} />
      </td>

      {/* YoY stability */}
      <td style={{ padding: '8px 6px', textAlign: 'center' }}>
        <span style={{
          fontSize: 10, fontFamily: 'var(--mono)', color: meta.yoy >= 0.5 ? '#10b981' : 'var(--text-3)',
        }}>
          {meta.yoy.toFixed(2)}
        </span>
      </td>

      {/* Status badge */}
      <td style={{ padding: '8px 12px' }}>
        {meta.status && (
          <span style={{
            display: 'inline-block', fontSize: 9, fontWeight: 700, letterSpacing: '0.06em',
            padding: '2px 7px', borderRadius: 3,
            color: status.color, background: status.bg,
            border: `1px solid ${status.color}40`,
          }}>
            {status.label.toUpperCase()}
          </span>
        )}
      </td>
    </tr>
  );
}

// ── Section table ──────────────────────────────────────────────────────────────

function MetricSection({
  title,
  subtitle,
  keys,
  meta,
  pitcherYears,
}: {
  title: string;
  subtitle: string;
  keys: NovelMetricKey[];
  meta: Record<NovelMetricKey, MetricMeta>;
  pitcherYears: Record<string, YearMetrics> | null;
}) {
  const rows = keys.map(k => ({
    key: k,
    yearValues: YEARS.map(yr => pitcherYears?.[yr]?.[k] ?? null),
  }));

  return (
    <div style={{ marginBottom: 20 }}>
      <div style={{ display: 'flex', alignItems: 'baseline', gap: 10, marginBottom: 10 }}>
        <span style={{ fontSize: 11, fontWeight: 600, color: 'var(--text-1)',
                       textTransform: 'uppercase', letterSpacing: '0.07em' }}>
          {title}
        </span>
        <span style={{ fontSize: 11, color: 'var(--text-3)' }}>{subtitle}</span>
      </div>
      <div style={{ border: '1px solid var(--border)', borderRadius: 'var(--radius-lg)', overflow: 'hidden' }}>
        <table style={{ width: '100%', borderCollapse: 'collapse' }}>
          <thead>
            <tr style={{ background: 'var(--bg-input)' }}>
              <th style={{ ...TH, textAlign: 'left' }}>Metric</th>
              <th style={{ ...TH, textAlign: 'left' }}>Dimension</th>
              <th style={{ ...TH, textAlign: 'right' }}>Value</th>
              <th style={{ ...TH, textAlign: 'center' }}>Dir</th>
              <th style={{ ...TH, textAlign: 'left' }}>2021–2025</th>
              <th style={{ ...TH, textAlign: 'left', minWidth: 100 }}>vs ERA (r)</th>
              <th style={{ ...TH, textAlign: 'center' }}>YoY r</th>
              <th style={{ ...TH, textAlign: 'left' }}>Status</th>
            </tr>
          </thead>
          <tbody>
            {rows.map(r => (
              <MetricRow
                key={r.key}
                metricKey={r.key}
                meta={meta[r.key]}
                yearMetrics={r.yearValues}
              />
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

const TH: React.CSSProperties = {
  padding: '7px 12px',
  fontSize: 10,
  fontWeight: 600,
  textTransform: 'uppercase',
  letterSpacing: '0.07em',
  color: 'var(--text-3)',
  fontFamily: 'var(--sans)',
  whiteSpace: 'nowrap',
};

// ── Summary strip ──────────────────────────────────────────────────────────────

function SummaryStat({ label, value, color }: { label: string; value: string | number; color?: string }) {
  return (
    <div style={{ textAlign: 'center', padding: '10px 20px' }}>
      <div style={{ fontSize: 22, fontFamily: 'var(--mono)', fontWeight: 500,
                    color: color ?? 'var(--text-1)', lineHeight: 1 }}>
        {value}
      </div>
      <div style={{ fontSize: 10, color: 'var(--text-3)', marginTop: 4,
                    textTransform: 'uppercase', letterSpacing: '0.06em' }}>
        {label}
      </div>
    </div>
  );
}

// ── Main component ─────────────────────────────────────────────────────────────

interface Props {
  pitcherId: number | string | null | undefined;
}

export function NovelMetricsPanel({ pitcherId }: Props) {
  const { data, meta, loading } = useNovelMetrics(pitcherId);

  const sortedKeys = useMemo(
    () => meta ? sortedByPredictiveness(meta) : [],
    [meta]
  );

  // Best metric for this pitcher (by absolute value vs direction)
  const bestMetric = useMemo(() => {
    if (!data || !meta) return null;
    const inModel = IN_MODEL.filter(k => data.latest[k] !== null && data.latest[k] !== undefined);
    if (!inModel.length) return null;
    return inModel.sort((a, b) => Math.abs(meta[b].r_test) - Math.abs(meta[a].r_test))[0];
  }, [data, meta]);

  if (loading) {
    return (
      <div className="card">
        <div className="card-title">Novel Metrics</div>
        <div className="loading">Loading metric data</div>
      </div>
    );
  }

  if (!data || !meta) {
    return (
      <div className="card">
        <div className="card-title">Novel Metrics</div>
        <div style={{ color: 'var(--text-3)', fontSize: 13, padding: '24px 0' }}>
          No novel metric data found for this pitcher.
          Run <code style={{ fontFamily: 'var(--mono)', fontSize: 11 }}>python models/export_novel_metrics_json.py</code> to generate.
        </div>
      </div>
    );
  }

  const latest = data.latest;
  const swingRv    = latest.swing_rv_against;
  const izSwingRv  = latest.in_zone_swing_rv;
  const bipAdjKbb  = latest.bip_adjusted_kbb;
  const takeRv     = latest.take_rv_against;
  const r2k        = latest.race_to_2_strikes;

  return (
    <div className="card">
      <div className="card-title">Novel Metrics Research Lab</div>

      {/* Summary strip */}
      <div style={{
        display: 'flex',
        background: 'var(--bg-input)',
        border: '1px solid var(--border)',
        borderRadius: 'var(--radius)',
        marginBottom: 20,
        overflow: 'hidden',
        flexWrap: 'wrap',
      }}>
        <SummaryStat label="Swing RV" value={swingRv !== null && swingRv !== undefined ? swingRv.toFixed(3) : '—'} color={swingRv !== null && swingRv !== undefined && swingRv < 0 ? '#10b981' : '#f43f5e'} />
        <div style={{ width: 1, background: 'var(--border)', alignSelf: 'stretch' }} />
        <SummaryStat label="IZ Swing RV" value={izSwingRv !== null && izSwingRv !== undefined ? izSwingRv.toFixed(3) : '—'} />
        <div style={{ width: 1, background: 'var(--border)', alignSelf: 'stretch' }} />
        <SummaryStat label="Take RV" value={takeRv !== null && takeRv !== undefined ? takeRv.toFixed(3) : '—'} />
        <div style={{ width: 1, background: 'var(--border)', alignSelf: 'stretch' }} />
        <SummaryStat label="BIP-Adj K-BB" value={bipAdjKbb !== null && bipAdjKbb !== undefined ? `${(bipAdjKbb * 100).toFixed(1)}%` : '—'} color={bipAdjKbb !== null && bipAdjKbb !== undefined && bipAdjKbb > 0 ? '#10b981' : '#f43f5e'} />
        <div style={{ width: 1, background: 'var(--border)', alignSelf: 'stretch' }} />
        <SummaryStat label="Race to 2K" value={r2k !== null && r2k !== undefined ? r2k.toFixed(2) : '—'} />
        <div style={{ width: 1, background: 'var(--border)', alignSelf: 'stretch' }} />
        <div style={{ marginLeft: 'auto', padding: '10px 18px', display: 'flex', flexDirection: 'column', justifyContent: 'center' }}>
          <div style={{ fontSize: 10, color: 'var(--text-3)', textTransform: 'uppercase', letterSpacing: '0.07em', marginBottom: 2 }}>
            Data years
          </div>
          <div style={{ fontFamily: 'var(--mono)', fontSize: 12, color: 'var(--text-2)' }}>
            {Object.keys(data.years).sort().join(' · ')}
          </div>
        </div>
      </div>

      {/* Legend row */}
      <div style={{ display: 'flex', gap: 16, marginBottom: 16, flexWrap: 'wrap' }}>
        {(['STRONG', 'WORTH', 'STABLE'] as const).map(s => (
          <div key={s} style={{ display: 'flex', alignItems: 'center', gap: 5 }}>
            <span style={{
              display: 'inline-block', width: 8, height: 8, borderRadius: 2,
              background: STATUS_CONFIG[s].color,
            }} />
            <span style={{ fontSize: 11, color: 'var(--text-3)' }}>
              {s === 'STRONG' ? 'Strong — in Pitch+ model (r>0.15, YoY>0.5)'
               : s === 'WORTH' ? 'Worth — in model (r>0.15)'
               : 'Stable — high YoY, used for pitch design only'}
            </span>
          </div>
        ))}
        <div style={{ marginLeft: 'auto', fontSize: 11, color: 'var(--text-3)' }}>
          vs ERA column = Pearson r on 2025 holdout (n=109 pitchers)
        </div>
      </div>

      {/* Section 1: In Pitch+ Model */}
      <MetricSection
        title="In Pitch+ Model"
        subtitle="— validated, actively contributing to pitcher scores"
        keys={IN_MODEL}
        meta={meta}
        pitcherYears={data.years}
      />

      {/* Section 2: Research stage */}
      <MetricSection
        title="Research Stage"
        subtitle="— computed but not yet meeting integration thresholds"
        keys={RESEARCH}
        meta={meta}
        pitcherYears={data.years}
      />

      {/* Section 3: Physical properties */}
      <MetricSection
        title="Physical Properties"
        subtitle="— high year-over-year stability, used for pitch design only"
        keys={PHYSICAL}
        meta={meta}
        pitcherYears={data.years}
      />
    </div>
  );
}
