/**
 * useNovelMetrics.ts
 *
 * Loads novel_metrics.json (generated by models/export_novel_metrics_json.py)
 * and exposes per-pitcher metric data + validation metadata.
 *
 * Data shape: 1903 pitchers × 14 metrics × 5 years (2.4 MB, cached after first fetch).
 */

import { useState, useEffect } from 'react';

// ── Types ──────────────────────────────────────────────────────────────────────

export interface MetricMeta {
  label: string;
  direction: 'lower' | 'higher';
  r_test: number;      // Pearson r vs ERA on 2025 holdout
  yoy: number;         // Year-over-year stability (Pearson r)
  status: 'STRONG' | 'WORTH' | 'STABLE' | '';
  dim: string;         // Pitch+ dimension or '—' if not integrated
}

export type NovelMetricKey =
  | 'race_to_2_strikes'
  | 'count_leverage_delta'
  | 'first_pitch_cascade'
  | 'first_pitch_skill'
  | 'memory_decay_effect'
  | 'arsenal_complementarity'
  | 'grav_dev_fb'
  | 'grav_dev_all'
  | 'bip_rate'
  | 'bip_adjusted_kbb'
  | 'swing_rv_against'
  | 'take_rv_against'
  | 'in_zone_swing_rv'
  | 'chase_swing_rv';

export type YearMetrics = Partial<Record<NovelMetricKey, number | null>>;

export interface NovelPitcherData {
  name: string;
  latest_year: number;
  latest: YearMetrics;
  years: Record<string, YearMetrics>;  // "2021" … "2025"
}

interface NovelMetricsFile {
  generated: string;
  metric_meta: Record<NovelMetricKey, MetricMeta>;
  n_pitchers: number;
  pitchers: Record<string, NovelPitcherData>;  // keyed by pitcher_id string
}

// ── Hook ───────────────────────────────────────────────────────────────────────

let _cache: NovelMetricsFile | null = null;
let _loading = false;
const _listeners: Array<() => void> = [];

function notifyListeners() {
  _listeners.forEach(fn => fn());
}

async function fetchOnce(): Promise<void> {
  if (_cache || _loading) return;
  _loading = true;
  try {
    const res = await fetch('/data/novel_metrics.json');
    if (!res.ok) throw new Error(`novel_metrics.json: HTTP ${res.status}`);
    _cache = await res.json() as NovelMetricsFile;
  } catch (e) {
    console.warn('[useNovelMetrics] failed to load:', e);
  } finally {
    _loading = false;
    notifyListeners();
  }
}

export function useNovelMetricsFile(): NovelMetricsFile | null {
  const [, forceUpdate] = useState(0);

  useEffect(() => {
    if (_cache) return;
    const fn = () => forceUpdate(n => n + 1);
    _listeners.push(fn);
    fetchOnce();
    return () => {
      const idx = _listeners.indexOf(fn);
      if (idx >= 0) _listeners.splice(idx, 1);
    };
  }, []);

  return _cache;
}

/**
 * Returns novel metric data for a single pitcher (by MLBAM pitcher_id).
 * Also returns the global metric metadata for rendering.
 */
export function useNovelMetrics(pitcherId: number | string | null | undefined): {
  data: NovelPitcherData | null;
  meta: Record<NovelMetricKey, MetricMeta> | null;
  loading: boolean;
} {
  const file = useNovelMetricsFile();

  if (!pitcherId) return { data: null, meta: null, loading: !_cache };

  const pid = String(pitcherId);
  const data = file?.pitchers[pid] ?? null;
  const meta = file?.metric_meta ?? null;

  return { data, meta, loading: !_cache };
}

/**
 * Get a sorted list of all metric keys by |r_test| (most predictive first).
 */
export function sortedByPredictiveness(
  meta: Record<NovelMetricKey, MetricMeta>
): NovelMetricKey[] {
  return (Object.keys(meta) as NovelMetricKey[]).sort(
    (a, b) => Math.abs(meta[b].r_test) - Math.abs(meta[a].r_test)
  );
}
