/**
 * useSparklines.ts — Load sparklines.json and trajectories.json
 *
 * sparklines.json is generated by trajectory.py --sparklines and contains
 * per-pitcher per-season metric values for trend visualisation.
 *
 * trajectories.json contains per-pitcher trajectory slope, label, and
 * confidence from the multi-year OLS regression.
 */

import { useState, useEffect } from 'react';
import { fetchJsonOrNull } from './fetchJson';

// ── Types ─────────────────────────────────────────────────────────────────────

export interface SeasonDataPoint {
  season: number;
  pitch_plus?: number;
  stuff?: number;
  command?: number;
  deception?: number;
  outcomes?: number;
  arsenal?: number;
  tunnel_and_sequence?: number;
}

export interface PitcherSparklines {
  [pitcherId: string]: SeasonDataPoint[];
}

export interface SparklinesJson {
  generated: string;
  pitchers: PitcherSparklines;
}

export interface TrajectoryEntry {
  pitcher_id: number;
  pitcher_name: string;
  seasons_observed: number;
  trajectory_slope: number | null;
  trajectory_confidence: number | null;
  trajectory_label: 'ascending' | 'declining' | 'plateau' | 'volatile' | 'insufficient_data';
  pitch_plus_latest: number | null;
  stuff_slope: number | null;
  command_slope: number | null;
  outcomes_slope: number | null;
}

export interface TrajectoriesJson {
  generated: string;
  n_pitchers: number;
  trajectories: TrajectoryEntry[];
}

// ── Singletons (load once, shared across components) ─────────────────────────

let sparklineCache: SparklinesJson | null = null;
let sparklinePromise: Promise<SparklinesJson | null> | null = null;

let trajectoryCache: TrajectoriesJson | null = null;
let trajectoryPromise: Promise<TrajectoriesJson | null> | null = null;

async function loadSparklines(): Promise<SparklinesJson | null> {
  if (sparklineCache) return sparklineCache;
  if (sparklinePromise) return sparklinePromise;
  sparklinePromise = fetchJsonOrNull<SparklinesJson>('/data/sparklines.json')
    .then((d) => { sparklineCache = d; return d; });
  return sparklinePromise;
}

async function loadTrajectories(): Promise<TrajectoriesJson | null> {
  if (trajectoryCache) return trajectoryCache;
  if (trajectoryPromise) return trajectoryPromise;
  trajectoryPromise = fetchJsonOrNull<TrajectoriesJson>('/data/trajectories.json')
    .then((d) => { trajectoryCache = d; return d; });
  return trajectoryPromise;
}

// ── Hook: sparklines for a single pitcher ────────────────────────────────────

export function usePitcherSparklines(pitcherId: number): SeasonDataPoint[] {
  const [points, setPoints] = useState<SeasonDataPoint[]>([]);
  useEffect(() => {
    loadSparklines().then((d) => {
      setPoints(d?.pitchers[String(pitcherId)] ?? []);
    });
  }, [pitcherId]);
  return points;
}

// ── Hook: trajectory for a single pitcher ────────────────────────────────────

export function usePitcherTrajectory(pitcherId: number): TrajectoryEntry | null {
  const [entry, setEntry] = useState<TrajectoryEntry | null>(null);
  useEffect(() => {
    loadTrajectories().then((d) => {
      setEntry(d?.trajectories.find((t) => t.pitcher_id === pitcherId) ?? null);
    });
  }, [pitcherId]);
  return entry;
}
